apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-microservice
  namespace: medicure
  labels:
    app: medicure-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure-microservice
  template:
    metadata:
      labels:
        app: medicure-microservice
    spec:
      containers:
      - name: medicure-microservice
        image: sagmaddy/medicure:v1
        ports:
        - containerPort: 8088
